"""add nullable True in some tables

Revision ID: 9a828ef9ebb1
Revises: 248a3df81850
Create Date: 2023-10-14 16:28:12.167777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a828ef9ebb1'
down_revision: Union[str, None] = '248a3df81850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'order', 'outlet_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'order', 'customer_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'order', 'worker_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'visit', 'worker_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'visit', 'customer_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'visit', 'outlet_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'visit', 'order_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit', 'outlet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'outlet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
